name: Unit Tests

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '3.1.x', '5.0.x' ]
        
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET ${{ matrix.dotnet  }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet  }}

      - name: Restore Packages
        run: dotnet restore

      - name: Build (.NET Standard)
        if: ${{ matrix.dotnet != "5.0.x" }}
        run: dotnet build -c Debug -f netcoreapp3.1

      - name: Build (.NET Standard)
        if: ${{ matrix.dotnet == "5.0.x" }}
        run: dotnet build -c Debug -f net5.0

      - name: Unit Tests
        run: dotnet test
        env:
          orbit_client_id: ${{ secrets.ORBIT_CLIENT_ID }}
          orbit_client_secret: ${{ secrets.ORBIT_CLIENT_SECRET }}
