name: Unit Tests

on:
  pull_request:
    branches: master
  push:
    branches: master

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: false
  orbit_client_id: ${{ secrets.ORBIT_CLIENT_ID }}
  orbit_client_secret: ${{ secrets.ORBIT_CLIENT_SECRET }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Build (.NET Standard)
        run: |
          dotnet restore
          dotnet build "DragonFruit.Common.Data/DragonFruit.Common.Data.csproj" -c Debug -f netstandard2.0
          dotnet build "DragonFruit.Common.Data.Tests/DragonFruit.Common.Data.Tests.csproj" -c Debug -f netcoreapp3.1

      - name: Unit Tests
        run: dotnet test -f netcoreapp3.1
          
          
  test-net50:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build (.NET 5)
        run: |
          dotnet restore
          dotnet build -c Debug -f net5.0

      - name: Unit Tests
        run: dotnet test -f net5.0