name: Unit Tests

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Build
        run: |
          dotnet restore
          dotnet build -c Debug

      - name: Unit Tests
        run: dotnet test -v n
        env:
          orbit_client_id: ${{ secrets.ORBIT_CLIENT_ID }}
          orbit_client_secret: ${{ secrets.ORBIT_CLIENT_SECRET }}