name: Unit Tests

on:
  pull_request:
    branches: master
  push:
    branches: master

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: false
  orbit_client_id: ${{ secrets.ORBIT_CLIENT_ID }}
  orbit_client_secret: ${{ secrets.ORBIT_CLIENT_SECRET }}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet: [ '3.1.x', '5.0.x' ]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Build
        run: dotnet build -c Debug -p:CIServer=True;CIFramework=${{ matrix.dotnet }}

      - name: Unit Tests
        run: dotnet test